title: QY Niu's Log
theme: minima

# 定义自定义集合 (Collections)
# 注意：下面的 ideas 和 projects 必须相对于 collections 有两个空格的缩进
collections:
  ideas:
    output: true
  projects:
    output: true

# 项目代称映射表
project_mapping:
  projectA: "Rapid Characterization of Textile Fibers via Optical Microscopy｜基于光学显微成像的纺织纤维快速表征研究"
  projectA1: "Construction of Optical Microscopic Morphological Datasets for Textile Fibers｜纺织纤维光学显微形态学数据库构建"
  projectA2: "Exploration of Automated Fiber Identification via Computer Vision｜基于计算机视觉的纤维成分自动识别方案探索"
  projectA3: "Impact of Common Household Liquids on the Morphological Stability of Textile Fibers｜日常化学介质对纺织纤维形态的影响研究"
